version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "estoque_daily_diet"
    ports:
      - "5434:5432"
    expose:
      - "5432"
    volumes:
      - C:\Users\DioenD\PycharmProjects\DailyDiet\:\var\lib\postgres